### ISSUE TITLE
unable adding component in runtime.

### ISSUE THREAD

**Issue by Abab-bk** [GumpDev/componentable#3]
I'm just doing what README says:
![image](https://github.com/GumpDev/componentable/assets/55276676/6ac8d9bf-c079-4d8a-9582-2d9c139dc12f)
Error:
![image](https://github.com/GumpDev/componentable/assets/55276676/1072669b-1daa-496c-be59-d4a2d8c13b0d)
But the component was added:
![image](https://github.com/GumpDev/componentable/assets/55276676/b6287338-19bd-43e8-8aee-9e6034e99bc3)

**Comment by gumpdev** [comment]
Sorry, this is a bug, I will create a PR fixing it, but the componentable is not made to change components in runtime, try to use the **active** variable of the component, like:

```
EventBus.enable_select_nobs.connect(func (): 
    var mob_select_indicator: MobSelectIndicator = Component.find(self, "MobSelectIndicator")
    mob_select_indicator.active = true
)
EventBus.disable_select_nobs.connect(func (): 
    var mob_select_indicator: MobSelectIndicator = Component.find(self, "MobSelectIndicator")
    mob_select_indicator.active = false
)
```

When you set active as false, the component won't process the logic until active is true again
