### ISSUE TITLE
Some trouble about this plugin, component host not setted

### ISSUE THREAD

**Issue by Smalldy** [GumpDev/componentable#5]
Hello, I am looking for a lightweight component framework for godot4, I looked for this plugin, first of all thank you very much for your work.
I'll report some issues in use, I'm not sure if there's a mistake  I'm using or if it's an issue with the plugin itself.

After exploring, I've been able to create the component, however, the host of the component is not exported correctly and I can't get the host node in the inspector：
![image](https://github.com/user-attachments/assets/2f9212b3-3861-4c4a-87c6-57979b3658f6)
![image](https://github.com/user-attachments/assets/7a8e8937-b068-43e5-b1a6-ccf9a4205e79)
![image](https://github.com/user-attachments/assets/80819f88-b46a-48d8-b69a-5bcb220ee293)
The value of csg_box_3d is null.
This is the code gen by this plugin
```
@icon("res://addons/componentable/icons/Component.svg")
class_name CSGBox3DComponent extends Node

@export var active = true : set = _set_active
var csg_box_3d: CSGBox3D

func _set_active(_active: bool):
	active = _active
	set_process(active)
	set_process_input(active)
	set_physics_process(active)
```
csg_box_3d is not exported,  may be it should be:
```
@export var csg_box_3d:CSGBox3D = $"../.."
```

------- 

What should I do?

Others:

1. Of course, CSGBox3D doesn't have a modulate attribute, I just wrote it casually.
2. How to reuse component code, I noticed that the component seems to be bound to the host type, if different types of objects need the same component, do I need to copy the code separately to make a new component?

**Comment by gumpdev** [comment]
Hello! thanks for the feedback, the componentable was created to be used with the Componentable tab, so if you want to add a component to a node, just select it and go to componentable tab on DOCK_SLOT_RIGHT_UL, and check the component checkbox, the plugin will automatically set the host
